config/routes.rb
Rails.application.routes.draw do
  root 'pages#show'

  resources :users, only: [:index, :create]
  resources :leagues, only: [:index, :show, :new, :create], param: :slug do
    resources :picks
  end

  get '/sign-up', to: 'users#new', as: 'sign_up'
  get '/dashboard', to: 'users#show', as: 'dashboard'

  get '/log-in', to: 'sessions#new', as: 'log_in'
  post '/log-in', to: 'sessions#create'
  get '/log-out', to: 'sessions#destroy', as: 'log_out'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  validates :start, presence: true
  validates :home_id, presence: true, uniqueness: { scope: :away_id }
  validates :away_id, presence: true
  validates :week_id, presence: true

  belongs_to :week
  belongs_to :home_team, class_name: 'Team', foreign_key: :home_id
  belongs_to :away_team, class_name: 'Team', foreign_key: :away_id
  has_many :picks
end

app/models/league.rb
class League < ApplicationRecord
  has_secure_token :join_token

  validates :name, presence: true, uniqueness: true
  validates :slug, presence: true, uniqueness: true

  has_many :user_leagues
  has_many :users, through: :user_leagues

  before_validation :set_slug

  def grant_membership(user)
    return if users.include?(user)
    users << user
  end

  def self.find_by_slug(slug)
    find_by(slug: slug)
  end

  def to_param
    self.slug if slug
  end

  private

  def set_slug
    self.slug = name.parameterize if should_change_slug?
  end

  def should_change_slug?
    !name.blank? || name_changed?
  end
end

app/models/league_creator.rb
class LeagueCreator
  attr_reader :league, :user

  def initialize(league, user)
    @league = league
    @user = user
  end

  def save
    if league.save
      league.user_leagues.create(user_id: user.id, role: 1)
      return true
    end
    return false
  end
end

app/models/pick.rb
class Pick < ApplicationRecord
  validates :user_league_id, presence: true
  validates :team_id, presence: true
  validates :game_id, presence: true

  belongs_to :user_league
  belongs_to :team
  belongs_to :game

  def game_team_name
    team.name.capitalize
  end

  def game_week
    game.week.number
  end
end

app/models/season.rb
class Season < ApplicationRecord
  validates :year, presence: true, uniqueness: true

  has_many :weeks

  def current_week
    now = Time.current
    week = weeks.where("start_date <= ? AND end_date >= ?", now, now).limit(1).first
    week.nil? ? check_date(now) : week
  end

  def end_date
    weeks.max_by(&:end_date).end_date
  end

  def self.current
    where(active: true).first
  end

  def start_date
    weeks.min_by(&:start_date).start_date
  end

  private

  def check_date(date)
    first_week = weeks.first
    return first_week if date < first_week.start_date
  end
end

app/models/team.rb
class Team < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  validates :abbreviation, presence: true, uniqueness: true

  has_many :home_games, class_name: 'Game', foreign_key: :home_id
  has_many :away_games, class_name: 'Game', foreign_key: :away_id
  has_many :picks
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email_address, presence: true, uniqueness: true
  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :phone_number, uniqueness: true

  has_many :user_leagues
  has_many :leagues, through: :user_leagues

  def short_name
    "#{first_name.capitalize} #{last_name[0].upcase}."
  end
end

app/models/user_league.rb
class UserLeague < ApplicationRecord
  validates :user_id, presence: true, uniqueness: { scope: :league_id }
  validates :league_id, presence: true
  validates :role, presence: true

  belongs_to :user
  belongs_to :league
  has_one :pick

  enum role: { user: 0, admin: 1, super: 2 }
end

app/models/week.rb
class Week < ApplicationRecord
  validates :number, presence: true, uniqueness: { scope: :season_id }
  validates :start_date, presence: true
  validates :end_date, presence: true
  validates :season_id, presence: true

  belongs_to :season
  has_many :games

  default_scope { order(end_date: :asc) }

  def formatted_week_ending
    end_date.strftime('%B %-e, %Y')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :reject_users
  helper_method :require_user

  private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def reject_users
    redirect_to root_path if current_user
  end

  def require_user
    redirect_to root_path unless current_user
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  before_action :require_user, except: [:show]

  def show
    @league = League.find_by_slug(params[:slug])
    @current_week = Season.current.current_week
  end

  def new
    @league = League.new
  end

  def create
    @league = League.new(league_params)
    user_league = LeagueCreator.new(@league, current_user)

    if user_league.save
      redirect_to @league
    else
      render :new
    end
  end

  private

  def league_params
    params.require(:league).permit(:name, :join_token)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

end

app/controllers/picks_controller.rb
class PicksController < ApplicationController
  before_action :verify_membership
  before_action :league, only: [:show]

  def show
    @pick = Pick.find(params[:id])
  end

  def new
    @week = Season.current.current_week
  end

  def create
    @pick = Pick.new(pick_params)
    if @pick.save
      redirect_to league_pick_path(league, @pick)
    else
      render :new
    end
  end

  private

  def verify_membership
    redirect_to root_path if user_league.nil?
  end

  def league
    @league ||= League.find_by_slug(params[:league_slug])
  end

  def pick_params
    params.require(:pick).permit(:team_id, :game_id).merge(user_league_id: user_league.id)
  end

  def user_league
    @user_league ||= UserLeague.find_by(user_id: current_user.id, league_id: league.id)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :reject_users, except: [:destroy]

  def new
  end

  def create
    @user = User.find_by(email_address: params[:session][:email_address])
    if @user && @user.authenticate(params[:session][:password])
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :reject_users, only: [:new, :create]
  before_action :require_user, only: [:show]

  def show
    @user = User.find(session[:user_id])
  end

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      redirect_to dashboard_path
    else
      render :new
    end
  end

  private

  def user_params
    params.require(:user)
      .permit(:email_address, :first_name, :last_name, :phone_number, :password)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NflSuicideLeague</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if current_user %>
      <%= link_to "Log Out", log_out_path %>
    <% else %>
      <%= link_to "Log In", log_in_path %>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/leagues/new.html.erb
<%= form_for @league do |f| %>
  <%= f.label :name, 'League Name' %>
  <%= f.text_field :name %>
  <%= f.submit 'Create League' %>
<% end %>

app/views/leagues/show.html.erb
<%= @league.name %>

<%= link_to "Make Week ##{@current_week.number} Pick", new_league_pick_path(@league) %>

app/views/picks/new.html.erb
Week ending: <%= @week.formatted_week_ending %>

<% @week.games.each do |game| %>
  <p>
    Away Team: <%= game.away_team.abbreviation %>
    <%= button_to "Pick #{game.away_team.name.capitalize} to lose.", { controller: 'picks', action: 'create', pick: { team_id: game.away_team.id, game_id: game.id } }, method: :post %>
  </p>
  <p>
    Home Team: <%= game.home_team.abbreviation %>
    <%= button_to "Pick #{game.home_team.name.capitalize} to lose.", { controller: 'picks', action: 'create', pick: { team_id: game.home_team.id, game_id: game.id } }, method: :post %>
  </p>
<% end %>

app/views/picks/show.html.erb
<%= @league.name %>
<p><%= current_user.short_name %> - Week #<%= @pick.game_week %> Pick - <%= @pick.game_team_name %> to lose.</p>

app/views/users/new.html.erb
<%= form_for @user do |f| %>
  <%= f.label :email_address, 'E-Mail Address' %>
  <%= f.text_field :email_address %>
  <%= f.label :first_name, 'First Name' %>
  <%= f.text_field :first_name %>
  <%= f.label :last_name, 'Last Name' %>
  <%= f.text_field :last_name %>
  <%= f.label :password, 'Password' %>
  <%= f.password_field :password %>

  <%= f.submit 'Sign Up!' %>
<% end %>